# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  backend:
    image: imed1/backend
    restart: always
    ports:
      - 8082:8082
    environment:
      JENKINS_URL: http://jenkins:123456@jenkins:8080
      MONGO_DB_URL: mongodb://root:example@mongo:27017/admin
      PORT: 8082

  dashboard:
    image: imed1/dashboard
    restart: always
    ports:
      - 3002:3002

  jenkins:
    image: imed1/jenkins-wamya:lts
    restart: always
    ports:
      - 8085:8080
    volumes:
      - jenkins_home_wamya1:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home_wamya1: {}
